codecov:
  require_ci_to_pass: yes
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
flags:
  backend:
    paths:
      - "backend/src/"
    carryforward: false

ignore:
  - "backend/test/"
  - "frontend/src/tests/"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/obj/"
  - "**/bin/"
