services:
  backend:
    build:
      context: ./backend
    image: bidtool-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
    image: bidtool-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
